# Generated by Django 4.2.7 on 2023-11-25 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsgoal',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Optionally, choose an account for this goal.', null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.bankaccount'),
        ),
        migrations.AlterField(
            model_name='spendingbudget',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Optionally, choose an account for this budget.', null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.bankaccount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Choose an account for this transaction.', null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.bankaccount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Choose a category for this transaction.', null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.category'),
        ),
    ]
